import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const calendar = [
  {
    time: "06:00 AM - 07:00 AM",
    name: "Vata Flow",
    teacher: "Ekansh",
    days: [1, 2, 3, 4, 5],
  },
  {
    time: "7:00 AM - 8:00 AM",
    name: "Power Vinyasa Flow",
    teacher: "Anokhi",
    days: [1, 3, 5],
  },
  {
    time: "12:00 PM - 1:00 PM",
    name: "Vata Flow",
    teacher: "Megan",
    days: [0, 2, 4, 5, 6],
  },
  {
    time: "2:30 PM - 4:30 PM",
    name: "Handstand Studio",
    teacher: "Alyssa",
    days: [6],
  },
  {
    time: "6:30 PM - 7:30 PM",
    name: "Restorative Yoga",
    teacher: "Becca",
    days: [0, 2, 4],
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vata | yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span>vata yoga</span>
        </h1>

        <p className={styles.description}>
          <code>a vinyasa studio in NYC</code>
        </p>

        <div>
          <table className={styles.table}>
            <thead>
              <tr>
                <td></td>
                <td>Sunday</td>
                <td>Monday</td>
                <td>Tuesday</td>
                <td>Wednesday</td>
                <td>Thursday</td>
                <td>Friday</td>
                <td>Saturday</td>
              </tr>
            </thead>
            <tbody>
              {calendar.map(({ days, name, time, teacher }) => {
                return (
                  <tr>
                    <td>{time}</td>
                    {[0, 1, 2, 3, 4, 5, 6].map((day) => {
                      if (!days.includes(day)) {
                        return <td />;
                      }

                      return (
                        <td>
                          <div>{name}</div>
                          <div className={styles.teacher}>{teacher}</div>
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>vata | 584 Broadway | e@sk.io</footer>
    </div>
  );
};

export default Home;
