import Head from "next/head";
import { Nav } from "../nav/Nav";
import styles from "./Page.module.css";

interface PageProps {
  children: JSX.Element | JSX.Element[];
}

export function Page({ children }: PageProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>vata | yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="crossorigin"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Hi+Melody&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Nav />
      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <span>
          made with love |{" "}
          <a href="mailto:e@sk.io" rel="noreferrer" target="_blank">
            e@sk.io
          </a>
        </span>
      </footer>
    </div>
  );
}
